# Generated by Django 5.2.7 on 2025-10-23 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='f_name',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='l_name',
            new_name='LastName',
        ),
    ]
